# Hands-On Exercises

1. Create a 3x3 identity matrix using NumPy.

2. Generate a 2D array with random integers and compute the row-wise sum.

3. Create a 1D array with 10 evenly spaced values between 0 and 100.

4. Perform element-wise addition, multiplication, and division on two random arrays of size 4x4.

5. Find the maximum value and its index in a randomly generated array.

In [3]:
import pandas as pd
import numpy as np

In [4]:
# Create a 3x3 identity matrix

data1 = np.eye(3)
data1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
# 2D array with random integers and compute a row-wise sum


data2 = np.array([[1,2,3,4,5],[6,7,8,9,10], [3,5,7,9,5]])

row_sum =  np.sum(data2, axis=1)
print("Row-wise sum:", row_sum)

Row-wise sum: [15 40 29]


In [6]:
# Create a 1D array with 10 evenly spaced values between 0 and 100.


data3 = np.linspace(0,100,10)
data3

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [7]:
# Perform element-wise addition, multiplication, and division on two random arrays of size 4x4.

array1 = np.random.rand(4,4)
array2 = np.random.rand(4,4)

#multiplication

mult = array1 * array2

#addition

addition = array1 + array2

#division

division = np.divide(array1, array2)


print("array1:\n", array1)

print("array2:\n", array2)

print("\nElement Wise Multiplication:\n", mult)

print("\nElement Wise Addition:\n", addition)

print("\nElement Wise Division:\n", division)

array1:
 [[0.87820838 0.26177628 0.9847871  0.62233759]
 [0.68067286 0.15247721 0.71293865 0.32600853]
 [0.5310177  0.26699519 0.53568802 0.08374023]
 [0.07274238 0.284774   0.48491091 0.53118783]]
array2:
 [[0.05855857 0.05196222 0.09260769 0.51414403]
 [0.5315091  0.94309118 0.08764518 0.7744774 ]
 [0.98388388 0.55927649 0.1655567  0.57627617]
 [0.82543818 0.48866489 0.71318646 0.14142072]]

Element Wise Multiplication:
 [[0.05142663 0.01360248 0.09119886 0.31997116]
 [0.36178381 0.14379991 0.06248563 0.25248623]
 [0.52245976 0.14932413 0.08868674 0.0482575 ]
 [0.06004434 0.13915905 0.3458319  0.07512096]]

Element Wise Addition:
 [[0.93676695 0.3137385  1.07739479 1.13648162]
 [1.21218195 1.09556839 0.80058383 1.10048592]
 [1.51490158 0.82627167 0.70124472 0.6600164 ]
 [0.89818057 0.77343889 1.19809738 0.67260855]]

Element Wise Division:
 [[14.99709448  5.03781902 10.63396673  1.21043436]
 [ 1.28064197  0.16167812  8.13437408  0.42094001]
 [ 0.53971583  0.47739391  3.2356771   0.14

In [8]:
# Find the maximum value and its index in a randomly generated array.

rand_array = np.random.rand(3,3)

print(rand_array)

[[0.67382477 0.95601989 0.41908273]
 [0.98218651 0.59860794 0.99688003]
 [0.97602187 0.38520478 0.75264815]]


In [9]:
max_value = rand_array.max()

max_index = np.unravel_index(np.argmax(rand_array), rand_array.shape)

print("Maximum Value:\n", max_value)

print("\nMaximum Value Index Position:\n", max_index)

Maximum Value:
 0.9968800304195271

Maximum Value Index Position:
 (1, 2)
